### ISSUE TITLE
When going off duty, get a Duty report

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-android#19]
When going off-duty, show reports filed during shift (reuse search results)

**Comment by VitaliyGre** [comment]
@Sheeri Should it be Find Records or screen with Duty Report subheader (instead of Recently Boarded Vessels)? Or new screen wit different title, maybe subheader and the same items?

**Comment by Sheeri** [comment]
@VitaliyGre it should be like Find Records, except it should be all records since the shift started (since the last time the user set the duty toggle to "on"). 

For the field test we will want the duty report to be emailed to us, so we can double check that all the reports that were filed, actually got into Atlas. So functionality should be designed with this in mind (although that will be a separate issue filed.

**Comment by Sheeri** [comment]
Design as per https://mongodb.invisionapp.com/share/RWX43EEF567#/screens/415937302
