### ISSUE TITLE
No description field appears when a user selects "Other" for Activity, Fishery, Gear, or Catch

### ISSUE THREAD

**Issue by MikeyDubs** [WildAid/o-fish-android#308]
Description fields should appear after a user selects "Other" from ANY drop down menu, not just EMS. This includes Activity, Fishery, Gear, and Catch. Currently, this doesn't happen with Activity, Fishery, Gear, and Catch. 

Issue - Activity, Fishery, Gear:
![Screen Shot 2020-09-16 at 10 25 03 PM](https://user-images.githubusercontent.com/49571712/93412699-aa441880-f86b-11ea-8945-25104010ecc8.png)

![Screen Shot 2020-09-16 at 10 25 09 PM](https://user-images.githubusercontent.com/49571712/93412703-ad3f0900-f86b-11ea-9a14-8e82af39ae55.png)

Issue - Catch:
![Screen Shot 2020-09-16 at 10 25 54 PM](https://user-images.githubusercontent.com/49571712/93412718-b4661700-f86b-11ea-8e24-b5b1fb98ce06.png)

Should be - Activity, Fishery, Gear (follow iOS)
![Summary Copy](https://user-images.githubusercontent.com/49571712/93412749-c5af2380-f86b-11ea-9a79-c713872ca35c.png)

![Summary Copy1](https://user-images.githubusercontent.com/49571712/93412754-c8aa1400-f86b-11ea-9740-fe913d545f18.png)

Should be - Catch (follow iOS)
![Amount Copy](https://user-images.githubusercontent.com/49571712/93412786-de1f3e00-f86b-11ea-9a5a-84a241a9665d.png)

Look to how EMS is implemented and do the same for Activity, Fishery, Gear and Catch. Note that what should be stored in the database is the description when "Other" is selected. e.g. if Activity is "Other" and the description is "Sailing", then "Sailing" should be stored in the activity field in the database.

**Comment by am-MongoDB** [comment]
Note that this also requires Realm schema changes

**Comment by lebedynskyi** [comment]
@Sheeri as @am-MongoDB   mentioned. This is noit a bug. It hsouyld be **Enhancment** and lot of UI changes.. 
Everything should synced between clients

**Comment by Sheeri** [comment]
@am-MongoDB I don't think this needs Realm schema changes - The vision was that the text is stored in the field just like the regular menu data is stored in the field.

For example let’s say the Activity is “Other” and the description is “Sailing”. Then for activity, “Sailing” should be stored. We don’t need a flag that it was “other”.

Does that make sense?

I will change to enhancement, Mike put it as a bug because the design specified it, so according to the design not having it is a 'bug'.

**Comment by Sheeri** [comment]
BTW, the reason we are thinking we don't need to store "Other" with a separate description, is that Agencies can change their menus at any time. So let's say an agency has "Transiting" and has a few boardings but ends up removing the menu item. The boarding records will still have "Transiting" in them. 

The 'transiting' boarding records weren't 'other' before, but now they are, because they aren't on the menu now. So to make it easier all around, we would like whatever the data is, to be stored in the field, even if it wasn't on the original menu. (If that's possible, of course!)
