### ISSUE TITLE
text field styles

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-android#45]
field line thickness and color; spacing; as per https://docs.google.com/document/d/1P3mzpbmd1iaXudXnmArLdawOrDCdmhG4WMwXPC0682c/edit#bookmark=id.f8qe51xxjpe3 and InVision example https://mongodb.invisionapp.com/share/AHXMRTBBSCQ#/screens/420974425_Android-Login

**Comment by lebedynskyi** [comment]
@Sheeri @am-MongoDB 

As we discussed.. NOw we used default Android widget without customization.. Android have some limitation to change height and width of views from one place in styles. Wee need to change all views manually to close this ticket. It could take 1  - 2 days since it affects all layouts and all design.

Lets keep this tickec as low priority or close it.
