### ISSUE TITLE
Draft boarding changes location when you open it up (if you moved location before)

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-android#463]
Patrol summary shows proper location (so the saving location is definitely a draft issue on android)

**Comment by EduardHarutyunyan97** [comment]
@Sheeri 
this task is done :) 
Here is the branch link 

https://github.com/WildAid/o-fish-android/tree/o_fish_bf_463

**Comment by Sheeri** [comment]
Hi, please create a PR for this change so I can test and review.

**Comment by EduardHarutyunyan97** [comment]
@Sheeri https://github.com/WildAid/o-fish-android/pull/473

**Comment by Sheeri** [comment]
Re-opening, the code did not fix this issue.

**Comment by EduardHarutyunyan97** [comment]
Hey Sheeri :) 
I understood the problem.
it's because when you want to watch your "Draft Boardings", there's no existing "Record Boarding" screen, when you want to edit it, it navigates you to the "Basic Information" fragment, which is an editable page, and it shows your live location.
If you would to see your drafted board details, I will navigate you from the "Draft Boarding" screen to "Record Boarding"...

So what I need to do? :)

**Comment by EduardHarutyunyan97** [comment]
@Sheeri Done.
https://github.com/WildAid/o-fish-android/pull/486
