### ISSUE TITLE
New business - changed mind

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-android#471]

**Comment by EduardHarutyunyan97** [comment]
@Sheeri please write a description

**Comment by Sheeri** [comment]
To reproduce:

- On the Vessel Information page of a boarding, under "Last Delivery Date", click "Business"
- Then click "+ New Business"
- You can then select "Business" again, and instead of getting the menu of businesses, you can type in a new business.
This is for the use case where a user realizes their choice WAS in the menu. Is there a way they can "reset" so they can see the menu? Maybe by clicking another field and coming back, or going to another page and coming back?

**Comment by EduardHarutyunyan97** [comment]
@Sheeri when you clicked on the "Business" edit view, it always opens the page in which we have existing businesses.

You can check by pulling the "development" branch :)

**Comment by Sheeri** [comment]
Yes, this works now, thanks!
